### ISSUE TITLE
How we can crop a video in a square like in Instagram?

### ISSUE THREAD

**Issue by devendroid** [JessYanCoding/InsGallery#12]
I have not seen any feature to crop video, when we pick or record a video its shows as a square but when we picked it's not cropped as being with image, while Instagram does this same thing for both image and video, 
So can we achieve this with the current version of this library?

**Comment by JessYanCoding** [comment]
This feature will be implemented in a future version, if you need it now, you can use [this code](https://github.com/JessYanCoding/InsGallery/blob/master/picture_library/src/main/java/com/luck/picture/lib/instagram/PictureSelectorInstagramStyleActivity.java#L975).

see [Transcoder](https://github.com/natario1/Transcoder)

**Comment by devendroid** [comment]
I will try with this code and also wait for the future version, Thanks.

**Comment by JessYanCoding** [comment]
ok👌

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/InsGallery/commit/eeb031fef899b12f6d8f8ff07e27d702a989bb4e

This feature is complete，in the next version

**Comment by devendroid** [comment]
In the latest version of the Lib, video cropping is working for the videos from the gallery only, not for the camera,
Do I need to set any property for this?
