### ISSUE TITLE
关于项目中的视频剪辑功能

### ISSUE THREAD

**Issue by spysoos** [JessYanCoding/InsGallery#13]
关于项目中的视频剪辑功能无法继续下一步，还是 TODO 状态吗？

**Comment by JessYanCoding** [comment]
对的，目前剪切已经完成了，代码也更新了，播放剪切范围的视频和视频选择封面还在做

**Comment by spysoos** [comment]
高效，还以为会引入ffmpeg做视频剪辑，不知道MediaExtractor/MediaMuxer兼容性怎么样，不过我是了一下速度挺快的，就差个封面

**Comment by spysoos** [comment]
如果能提供一个压缩选项就更好了

**Comment by JessYanCoding** [comment]
本来使用的是第三方库 [mp4parser](https://github.com/JessYanCoding/InsGallery/blob/master/picture_library/src/main/java/com/luck/picture/lib/instagram/process/VideoClipUtils.java#L130)，速度比现在使用的 MediaCodec 的方式快几倍，但是在剪切精度上有一点问题，就换回系统自带的 MediaCodec，MediaCodec 是系统自带的，一般情况下兼容性没什么问题。
