### ISSUE TITLE
设置剪裁比例无效

### ISSUE THREAD

**Issue by spysoos** [JessYanCoding/InsGallery#16]
withAspectRatio(16, 9) 即使这样设置，出来的图片也还是正方形

**Comment by JessYanCoding** [comment]
对，因为instagram 的产品逻辑只有正方形和保持原有比例这两种选择，withAspectRatio 是 PicutureSelector 的选项我屏蔽了的，这个库前期的目的就是跟着 Instagram 的产品逻辑就走，现在提供其他比例，会影响原有 Ui 的展示和裁剪逻辑，会多很多代码以及需要一些未知的问题，所以暂时不支持
