### ISSUE TITLE
很棒，但是感觉有点写死了

### ISSUE THREAD

**Issue by moo611** [JessYanCoding/InsGallery#19]
大神你好，现在的项目里有如下需求
（1）不需要滤镜页面
（2）不需要选择视频的tab，只需要2个tab。
请问该怎么改呢？：）

**Comment by JessYanCoding** [comment]
前期的工作目标主要是以实现 instagram 的大部分功能为主，市面上也没可参考的其他开源库，全靠我自己一个人实现，工作量比较大，实现起来也比较慢，所以前期先把时间用来做功能实现，暂时不会太过考虑扩展性，后期功能实现完整且稳定后，才会注重扩展性，将某些功能可定制化。

以我写其他库的经验，将一个库扩展性做好是一个漫长且工作量比较大的过程，何况是一个 UI 库，就是从 0 到 1 实现这些功能需求，我也花费了几个月时间，所以这个库的成长是个漫长的过程，不可能一步到位，毕竟工作量在那摆着的，国内甚至国外很难看到业务需求这么复杂的相册了，前期先以稳定为主，你如果需要自定义你所说的这些功能，需要你自己导入本地代码改

**Comment by moo611** [comment]
非常感谢。我已经下载源码，并且尝试用您的方法。屏蔽滤镜的已经解决了，但是不需要拍视频，我把第260行的mList.add(new PageVideo(pagePhoto))注释掉，但是页面只停留在相册页面，无法切换。您如果有空可以试一下吗？

**Comment by moo611** [comment]
> 非常感谢。我已经下载源码，并且尝试用您的方法。屏蔽滤镜的已经解决了，但是不需要拍视频，我把第260行的mList.add(new PageVideo(pagePhoto))注释掉，但是页面只停留在相册页面，无法切换。您如果有空可以试一下吗？

**Comment by moo611** [comment]
> 前期的工作目标主要是以实现 instagram 相册的大部分功能为主，市面上也没可参考的其他 Instagram 开源相册，全靠我自己一个人实现，工作量比较大，实现起来也比较慢，所以前期先把时间用来做功能实现，暂时不会太过考虑扩展性，后期功能实现完整且稳定后，才会注重扩展性，将某些功能可定制化。
> 
> 以我写其他库的经验，将一个库扩展性做好是一个漫长且工作量比较大的过程，何况是一个 UI 库，就是从 0 到 1 实现这些功能需求，我也花费了几个月时间，所以这个库的成长是个漫长的过程，不可能一步到位，毕竟工作量在那摆着的，国内甚至国外都很难看到业务需求以及集成度这么复杂的开源相册了，所以前期先以稳定为主，你如果需要自定义你所说的这些功能，需要你自己导入本地代码改。
> 
> 屏蔽滤镜的话，你就需要让他在选择时不要跳转这个 Activity
> https://github.com/JessYanCoding/InsGallery/blob/master/picture_library/src/main/java/com/luck/picture/lib/instagram/process/InstagramMediaProcessActivity.java
> 
> 不需要拍摄视频，需要屏蔽这的代码 https://github.com/JessYanCoding/InsGallery/blob/master/picture_library/src/main/java/com/luck/picture/lib/instagram/PictureSelectorInstagramStyleActivity.java#L256

**Comment by moo611** [comment]
非常感谢。我已经下载源码，并且尝试用您的方法。屏蔽滤镜的已经解决了，但是不需要拍视频，我把第260行的mList.add(new PageVideo(pagePhoto))注释掉，但是页面只停留在相册页面，无法切换。您如果有空可以试一下吗？

**Comment by moo611** [comment]
第二个也解决了，除了注释掉260行之外，我把isTranslateX的判断去掉变成了`for (View view : mViews) {
            view.setTranslationX(scrollHorizontalPosition);
        }`就好了。非常感谢提供这么好的框架：）

**Comment by JessYanCoding** [comment]
好的
