### ISSUE TITLE
support：希望支持批量一键裁剪

### ISSUE THREAD

**Issue by lanzhu1993** [JessYanCoding/InsGallery#2]
当选择选择多张图片后，进入裁剪页面，选择底部的最后一张裁剪，然后点击完成，前面所有图片都没裁剪，只有最后一张才有裁剪操作，希望支持一键裁剪，不用一张张的点。

**Comment by JessYanCoding** [comment]
好的，后面裁剪这都会重构的，现在这里用的都是 [UCrop](https://github.com/Yalantis/uCrop) 的逻辑

**Comment by JessYanCoding** [comment]
新版本已添加，批量裁剪，批量滤镜功能
