### ISSUE TITLE
getCurrentTheme is null

### ISSUE THREAD

**Issue by azamatdev** [JessYanCoding/InsGallery#23]
I followed just like the example app. but it shows

Attempt to invoke virtual method 'int com.luck.picture.lib.instagram.InstagramSelectionConfig.getCurrentTheme()' on a null object reference

What could be the cause?

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/InsGallery/blob/master/picture_library/src/main/java/com/luck/picture/lib/instagram/InsGallery.java#L112

**Comment by JessYanCoding** [comment]
Cannot be null here

**Comment by azamatdev** [comment]
I debugged it, yeah u are right it cant be null. It has values. But this error keeps popping up. Even I run your sample project used maven implementation instead of your library package( in your example u used ur package as module, not maven implementation). The same error occurred. Before calling open Gallery I am setting the THEME too, but no success.  

`    InsGallery.setCurrentTheme(InsGallery.THEME_STYLE_DEFAULT) ---
     InsGallery.openGallery(
                this,
                GlideEngine.createGlideEngine(),
                GlideCacheEngine.createCacheEngine(),
                listOfMedia
            );`

What do you think, What can be the cause??? I followed all the steps in your sample. You can try the lib, in a new project

**Comment by JessYanCoding** [comment]
My company's project uses maven implementation，the following is the code，not error。

```java
InsGallery.setCurrentTheme(currentTheme);
InsGallery.openGallery(Activity, GlideEngine.createGlideEngine(), GlideCacheEngine.createCacheEngine(), null);
```

I think this is a very simple problem, I suggest you debug it yourself。

**Comment by azamatdev** [comment]
This issue still exists, I debugged it. 
![image](https://user-images.githubusercontent.com/29502563/92299154-449d8580-ef69-11ea-8186-a0512ae10aa4.png)


It shows null pointer, but when i debug it everything seems to be good
![image](https://user-images.githubusercontent.com/29502563/92299196-a78f1c80-ef69-11ea-9c6d-3c3fa468bbec.png)

I followed all the code u provided in your sample, I double check it. When run your sample, used your lib as a maven dependency, it showed the same error

![image](https://user-images.githubusercontent.com/29502563/92299224-efae3f00-ef69-11ea-96db-20e70b60d938.png)
here I Used maven dependency instead of project dependency. But no luck.

**Comment by hejj** [comment]
请问下这个问题解决了吗？我遇到了相同了问题

**Comment by hejj** [comment]
请问下这个问题解决了吗？我遇到了相同了问题

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/InsGallery/blob/c3df73c1c88ef839702cf02f33cbc59b04feeb42/picture_library/src/main/java/com/luck/picture/lib/instagram/InsGallery.java#L112

Call this method yourself
