### ISSUE TITLE
多选是否可以添加一个是否裁剪

### ISSUE THREAD

**Issue by zhaoweiguo5505** [JessYanCoding/InsGallery#4]
多选那里 感觉添加一个是否裁剪的选项的 好一点 有一些照片不需要裁剪  但是现在的逻辑是 多选的话 就要一张张裁剪，体验感不太好

**Comment by JessYanCoding** [comment]
后期会完全改成 instagram  那种方式，自动批量裁剪，单击可对单个图片进行调整的模式，第一个版本没有对多图剪切这的逻辑进行修改，全部使用的是 [uCrop](https://github.com/Yalantis/uCrop) 这个库的代码逻辑。
