### ISSUE TITLE
Unable to use the Library

### ISSUE THREAD

**Issue by HaXxanParhar** [JessYanCoding/InsGallery#47]
I'm new to Android and there's very little guidance on how to use the library. In fact, there is only one line on usage and after pasting that line in my activity, It was missing the GlideEngine. I found the GlideEngine online and fixed that issue. But the next parameter was the OnResultCallBack which required the GridImageAdapter and both of these resist in the library but I'm calling the openGallery() function from my Activity so how am I supposed to pass the mAdapter (GridImageAdapter) there? When I don't have it in my activity neither I can access it from the library. I know it must be very easy to use but I just couldn't figure out how to use it as I'm new to the programming. Kindly help with this. Thanks

**Comment by JessYanCoding** [comment]
emmm...  GridImageAdapter is to display photo album pictures，replace GridImageAdapter with Adapter in your project。

Considering that you are a new programmer, it is recommended that you copy GridImageAdapter to your project

**Comment by HaXxanParhar** [comment]
Thank you :)
